server:
  port: 8088

spring:
  logging:
    level:
      root: WARN
      com.spiderwalk: DEBUG
      org.springframework.web: INFO
      org.springframework.security: INFO
  datasource:
    platform: postgres
    url: jdbc:postgresql://host.docker.internal:5432/mezzanine-test
    username: mezzanine-test
    password: mezzanine-test
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: scheduler
        hbm2ddl:
          auto: create-drop
cron:
  expression: "*/10 * * * * *"